### PR TITLE
Update config_es

### PR DESCRIPTION
**Pull request by carmen890**

### CODE REVIEW

**Comment by chris-blues** [comment]
Hi Florent!
This patch looks ok to me, though I don't speak any spanish, so maybe you want to check for yourself? Otherwise I could just merge it...
Cheers

**Comment by frougon** [comment]
Yes, but it doesn't seem to be based on the up-to-date master, so the merge won't be fast-forward, which is not very clean. I'm exchanging emails with Carmen about all this, don't worry. :-)

**Comment by chris-blues** [comment]
Okeydokey!

**Comment by frougon** [comment]
Hmm, apparently Carmen has fixed this? I must check. I still have a screenshot showing the first patch-2 branch was based on frougon's master HEAD^ commit (parent of HEAD). :-)

**Comment by chris-blues** [comment]
Well, it has the new multiplayer testing options...

**Comment by carmen890** [comment]
What did I fix that I haven't realized? lol

**Comment by chris-blues** [comment]
If I understand correctly, frougon had the feeling, that your HEAD was not in sync with frougon's HEAD...
But I can see no evidence of that so far. (Then again, I'm no git guru...)
The line about terrasync being defaulted to $FGHOME/terrasync is missing too, so I'd think it's up to date. (c1055c5a9abed9855c37ef8c2ede91afdeb29bef)

**Comment by frougon** [comment]
Yes, history seems good now, and the last corrections too. :-)

**Comment by carmen890** [comment]
I'm glad it worked but I have no idea of what I've done :)

**Comment by chris-blues** [comment]
Great! Now we have an up-to-date spanish config! Thanks!
Do you think about translating the rest too?

**Comment by frougon** [comment]
Argh, this GitHub merge button is crap! That's what Linus said, but now I understand why.

Carmen's history was fine: linear, based on my latest commit (commit 619bf70fc7d62bf41ce837ebcd724950c9287985 from Carmen is not a merge commit: it has only one parent, which was the latest commit on my master branch just before I pressed the 'Merge request' button). But when I pressed this button, GitHub automatically created a useless merge commit on my behalf. It is completely useless, because it is absolutely identical to Carmen's one, it just clutters history.

It is not a big deal once in a while, and now I know what to expect, but the SourceForge "merge feature" works much better (that's what Edward d'Auvergne said on the FG list). Next time, I'll try on the command line, not with the GitHub button...

Translation of the rest: yes, we talked about it, I gave Carmen instructions...

**Comment by chris-blues** [comment]
That's good news! \o/
I too was just wondering, why it took 2 commits... oh well...

**Comment by carmen890** [comment]
I didn't undertand a word. I'm new here. But no problem ;)
Next time I'll just send you the files and that's all.

**Comment by chris-blues** [comment]
No, all was fine! It just looked strange, but that's not your fault, but github's...

**Comment by frougon** [comment]
And the GitHub  thing is very vicious (sorry if wrong word: this is French more or less): when I updated my clone:

% git pull
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 7 (delta 3), reused 7 (delta 3), pack-reused 0
Unpacking objects: 100% (7/7), done.
From github.com:frougon/FFGo
   c1055c5..72ceab9  master     -> origin/master
Updating c1055c5..72ceab9
Fast-forward
 ffgo/data/config/config_es | 124 ++++++++++++++++++++++++++++++++++++++-------
 1 file changed, 107 insertions(+), 17 deletions(-)
%

As you can see, it says "Fast-forward", which means: linear history, no ugly merge. Because the merge commit was created directly on the SF repo, not by myself. So my clone has been fast-forwarded to the latest commit on the SF repo, which made it advance by 2 commits instead of 1 as I expected (first one: carmen; second commit: useless merge commit).

Yes, Carmen, don't worry. When you read the Git docs I gave you the URL's of, you'll understand better.

**Comment by carmen890** [comment]
I wasn't worrying hahaha.
So much to learn in so little time.
I'll catch up

**Comment by frougon** [comment]
Next time: either send the files, or maybe you can commit in your clone and I can try to merge manually on my side, without the GitHub button. I think this should be doable, because I carefully checked your history and your commit was a proper direct descendant of my last one: c1055c5a9abed9855c37ef8c2ede91afdeb29bef

**Comment by chris-blues** [comment]
Yes it takes a little while, to get going, but then it becomes rather easy...

**Comment by chris-blues** [comment]
OK, good night folks! @Carmen: keep it coming! Great job!

**Pull request merged**
